eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9091/eureka/
fetch-registry: true
management:
    security:
        enabled: false
register-with-eureka: true
server:
    port: 8484
spring:
    application:
        name: user-service
#    data:
#        mongodb:
#            uri: mongodb://localhost:27017/mongodb2

